version : "3"

services:
    db:
       image: postgres
       environment:
        - "POSTGRES_HOST_AUTH_METHOD=trust"
    dj: 
       container_name: dja 
       build: django # django's Dockerfile path
       command: python manage.py runserver 0.0.0.0:90
       volumes:
       - ./django:/code
       
       ports:
        - "90:90"
       depends_on:
        - db